#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# aria2 Manager

url=
file=

clear
banner

echo ''
echo '-------------------------------------------'
echo '                aria2 Manager'
echo ''
echo ' Downloads are in Internal Storage/Download'
echo '-------------------------------------------'

echo ''
echo 'Enter URL: '
read url
echo ''
echo 'Enter filename: '
read file
echo ''

aria2c -d Download -c -x 4 -k 1M --file-allocation=none -o "$file" "$url"

echo ''
echo 'Task finished.'
echo 'Press ENTER to return to aria2manager'
read tmp
sh aria2manager
