#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# aria2 Manager

url=
file=

clear
banner

echo ''
echo '-------------------------------------------'
echo '                aria2 Manager'
echo ''
echo ' Downloads are in Internal Storage/Download'
echo '-------------------------------------------'

echo ''
echo 'Enter 0 as URL to go back'
echo 'Enter URL: '
read url
if [ $url -eq 0 ]
then
    clear
    index
fi
echo ''
echo 'Enter filename: '
read file
echo ''

aria2c -d Download -c -x 4 -k 1M --file-allocation=none -o "$file" "$url"
