#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# Banner

echo '************************************************'
echo ''
echo '                The Termux Project'
echo ''
echo '            Last updated - 17/Oct/2020'
echo ''
echo '************************************************'
