#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# Banner

echo '************************************************'
echo ''
echo '                 Testing updater 2'
echo ''
echo '            - adithyassekhar 25/May/2020'
echo ''
echo '************************************************'
echo ''
echo "Current directory is `pwd`"
