#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# Index page

banner

echo ''
echo '1. WaStatus'
echo ''
echo '2. aria2 Manager'
echo ''
echo '3. youtube-dl'
echo ''
echo '4. Update'
echo ''
echo '5. Uninstall'
echo ''
echo 'Press ENTER to skip this menu'
echo ''

read i
if [ $i -eq 1 ]
then
	wastatus
elif [ $i -eq 2 ]
then
	aria2manager
elif [ $i -eq 3 ]
then
	yt
elif [ $i -eq 4 ]
then
echo ''
echo 'Starting update'
echo ''
cd /data/data/com.termux/files/usr/etc >/dev/null 2>&1
rm bash.bashrc >/dev/null 2>&1
mv bash.bashrc.bak bash.bashrc >/dev/null 2>&1
cd ~
rm remote-install.sh
curl 'https://raw.githubusercontent.com/adithya-s-sekhar/the-termux-project/master/remote-install.sh' -o remote-install.sh >/dev/null 2>&1
sh remote-install.sh && echo
elif [ $i -eq 5 ]
then
echo 'Do you want to uninstall (y/n): '
read u
if [ $u = "y" ]
then
cd ~
cd the-termux-project
sh uninstall.sh && echo
else
clear
index
fi
else
	clear
fi
