#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# Index page

ETC=~/../usr/etc

banner

echo ''
echo 'Available scripts'
echo '--------------'
echo ''
echo '1. WaStatus'
echo ''
echo '2. aria2 Manager'
echo ''
echo "3. youtube-dl (You can also 'share' links to termux)"
echo ''
echo '4. Update/Reinstall'
echo ''
echo '5. Uninstall'
echo ''
echo 'Press ENTER to skip this menu'
echo ''
echo 'Choose option: '
read i
if [ $i -eq 1 ]
then
	wastatus
elif [ $i -eq 2 ]
then
	aria2manager
elif [ $i -eq 3 ]
then
	yt
elif [ $i -eq 5 ]
then
	echo 'Do you want to uninstall (y/n): '
	read u
	if [ $u = "y" ]
	then
		cd ~
		cd the-termux-project
		sh uninstall.sh && echo
	else
		clear
		index
	fi
elif [ $i -eq 4 ]
then
	echo ''
	echo 'Starting update'
	echo ''
	cd $ETC >/dev/null 2>&1
	rm bash.bashrc >/dev/null 2>&1
	mv bash.bashrc.bak bash.bashrc >/dev/null 2>&1
	cd ~
	rm remote-install.sh
	pkg install git >/dev/null 2>&1
	git clone --depth 1 https://github.com/adithya-s-sekhar/the-termux-project >/dev/null 2>&1
	cd the-termux-project
	sh install.sh && echo
else
	clear
fi
