#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# More page

ETC=~/../usr/etc

clear
banner

echo ''
echo 'Current release: v0.2 - 19/Aug/2020'
echo ''
echo 'Changelog of current version'
echo "* add 'p' to end of resolution in downloaded filename"
echo '* now shows dependency installation errors if it happens'
echo "  - use 'update' function to reinstall missing dependancies if it happens"
echo '  - python and by effect youtube-dl are the main offenders'
echo '* minor updates to instructions and UI tweaks'
echo '* proper finishing messages'
echo '* returns to current script after finishing'
echo '* start using github releases'
echo ''
echo 'https://github.com/adithya-s-sekhar/the-termux-project'
echo ''
echo '1. Update/Reinstall'
echo ''
echo '2. Uninstall'
echo ''
echo 'Press ENTER to go back'
echo ''
echo 'Choose option: '
read i
if [ $i -eq 2 ]
then
	echo 'Do you want to uninstall (y/n): '
	read u
	if [ $u = "y" ]
	then
		cd ~
		cd the-termux-project
		sh uninstall.sh && echo
	else
		clear
		index-more
	fi
elif [ $i -eq 1 ]
then
	echo ''
	echo 'Starting update'
	echo ''
	cd $ETC >/dev/null 2>&1
	rm bash.bashrc >/dev/null 2>&1
	mv bash.bashrc.bak bash.bashrc >/dev/null 2>&1
	cd ~
	rm remote-install.sh
	curl 'https://raw.githubusercontent.com/adithya-s-sekhar/the-termux-project/master/remote-install.sh' -o remote-install.sh >/dev/null 2>&1
	sh remote-install.sh && echo
else
	clear
	index
fi
