#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# Index page

ETC=~/../usr/etc

banner

echo ''
echo 'Available scripts'
echo '--------------'
echo ''
echo '1. WaStatus'
echo ''
echo '2. aria2 Manager'
echo ''
echo "3. youtube-dl (You can also 'share' links to termux)"
echo ''
echo '4. More'
echo ''
echo 'Press ENTER to skip this menu'
echo ''
echo 'Choose option: '
read i
if [ $i -eq 1 ]
then
	wastatus
elif [ $i -eq 2 ]
then
	aria2manager
elif [ $i -eq 3 ]
then
	yt
elif [ $i -eq 4 ]
then
	more
else
	clear
fi
