#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# WaStatus - Audio Module

wa_aud=
wa_img=
wa_start=
wa_end=
wa_out=
wa_scale=
wa_scalew=
wa_scaleh=
wa_maxdata=1692k
wa_bufsize=1692k

clear
banner
wastatus-banner

echo 'Audio Status'
echo '------------'
echo ''
echo 'Input audio file (with extension): '
read wa_aud
echo ''
echo "Background image ('cover' to select albumart): "
read wa_img
echo ''
echo 'Start time: '
read wa_start
echo ''
echo 'End time: '
read wa_end
echo ''
echo 'Output filename: '
read wa_out
echo ''

echo 'Resize video (y/n): '
read wa_scale
echo ''
if [ $wa_scale = "n" ]
then
	if [ $wa_img = "cover" ]
	then
		ffmpeg -i "$wa_aud" -an "tmp_$wa_aud.jpg"
		ffmpeg -i "$wa_aud" -c copy -ss $wa_start -to $wa_end "tmp_$wa_aud.mka"
		ffmpeg -loop 1 -i "tmp_$wa_aud.jpg" -i "tmp_$wa_aud.mka" -c:v libx264 -preset faster -crf 25 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -pix_fmt yuv420p -c:a aac -b:a 64k -shortest "$wa_out.mp4"
		rm "tmp_$wa_aud.mka"
		rm "tmp_$wa_aud.jpg"
	else
		ffmpeg -i "$wa_aud" -c copy -ss $wa_start -to $wa_end "tmp_$wa_aud.mka"
		ffmpeg -loop 1 -i "$wa_img" -i "tmp_$wa_aud.mka" -c:v libx264 -preset faster -crf 25 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -pix_fmt yuv420p -c:a aac -b:a 64k -shortest "$wa_out.mp4"
		rm "tmp_$wa_aud.mka"
	fi
elif [ $wa_scale = "y" ]
then
	echo 'Resize Width: '
	read wa_scalew
	echo ''
	echo 'Resize Height: '
	read wa_scaleh
	echo ''
	if [ $wa_img = "cover" ]
	then
		ffmpeg -i "$wa_aud" -an "tmp_$wa_aud.jpg"
		ffmpeg -i "$wa_aud" -c copy -ss $wa_start -to $wa_end "tmp_$wa_aud.mka"
		ffmpeg -loop 1 -i "tmp_$wa_aud.jpg" -i "tmp_$wa_aud.mka" -c:v libx264 -preset faster -crf 25 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -pix_fmt yuv420p -vf "scale=$wa_scalew:$wa_scaleh" -c:a aac -b:a 64k -shortest "$wa_out.mp4"
		rm "tmp_$wa_aud.jpg"
		rm "tmp_$wa_aud.mka"
	else
		ffmpeg -i "$wa_aud" -c copy -ss $wa_start -to $wa_end "tmp_$wa_aud.mka"
		ffmpeg -loop 1 -i "$wa_img" -i "tmp_$wa_aud.mka" -c:v libx264 -preset faster -crf 25 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -pix_fmt yuv420p -vf "scale=$wa_scalew:$wa_scaleh" -c:a aac -b:a 64k -shortest "$wa_out.mp4"
		rm "tmp_$wa_aud.mka"
	fi
fi
