#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# WaStatus - Primary Module

x=

clear
banner
wastatus-banner

echo ''
echo '1. Video status'
echo ''
echo '2. Audio status'
echo ''
echo 'Choose option: '

read x

if [ $x -eq 1 ]
then
 wastatus-video
elif [ $x -eq 2 ]
then
 wastatus-audio
else
 wastatus
fi
