#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# Initial Date: 09/May/2020
# Current Date: 09/May/2020
# WaStatus - Banner

echo '-----------------------------------'
echo '    WhatsApp Status Creater Tool'
echo '-----------------------------------'
