#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# WaStatus - Banner

echo ''
echo '-----------------------------------'
echo '    WhatsApp Status Creater Tool'
echo ''
echo ' Files should be in root of internal storage'
echo '-----------------------------------'
