#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# WaStatus - Video Module

wa_in=
wa_off=
wa_start=
wa_end=
wa_out=
wa_scale=
wa_crop=
wa_tran=
wa_cropw=
wa_croph=
wa_scalew=
wa_scaleh=
wa_maxdata=
wa_bufsize=
k=k

clear
banner
wastatus-banner

echo 'Video Status'
echo '------------'
echo ''
echo 'Input file (with ext): '
read wa_in
echo ''
echo 'Start Offset: '
read wa_off
echo ''
echo 'Start time: '
read wa_start
echo ''
echo 'End time: '
read wa_end
echo ''
echo 'Max datarate (KBps): '
read wa_maxdata
wa_maxdata=$((wa_maxdata*8-64))
wa_maxdata="$wa_maxdata$k"
wa_bufsize=$((wa_maxdata*2))
wa_bufsize="$wa_bufsize$k"
echo ''
echo 'Output filename (with ext): '
read wa_out
echo ''

echo 'Crop Video (y/n): '
read wa_crop
echo ''
echo 'Resize video (y/n): '
read wa_scale
echo ''
echo 'Transpose (y/n): '
read wa_tran
echo ''

#using binary for true or false
#crop-scale-transpose

#1-1-1

if [ $wa_crop = "y" ] && [ $wa_scale = "y" ] && [ $wa_tran = "y" ]
then
	echo 'Cropping source video'
	echo 'Crop Width: '
	read wa_cropw
	echo ''
	echo 'Crop Height: '
	read wa_croph
	echo ''
	echo 'Resizing cropped video'
	echo 'Resize Width: '
	read wa_scalew
	echo ''
	echo 'Resize Height: '
	read wa_scaleh
	echo ''
	ffmpeg -ss $wa_off -i $wa_in -ss $wa_start -to $wa_end -vf "crop=$wa_cropw:$wa_croph:x:y,scale=$wa_scalew:$wa_scaleh,transpose=1" -preset faster -crf 18 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k $wa_out
fi

#1-0-1

if [ $wa_crop = "y" ] && [ $wa_scale = "n" ] && [ $wa_tran = "y" ]
then
	echo 'Cropping source video'
	echo 'Crop Width: '
	read wa_cropw
	echo ''
	echo 'Crop Height: '
	read wa_croph
	echo ''
	ffmpeg -ss $wa_off -i $wa_in -ss $wa_start -to $wa_end -vf "crop=$wa_cropw:$wa_croph:x:y,transpose=1" -preset faster -crf 18 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k $wa_out
fi

#1-1-0

if [ $wa_crop = "y" ] && [ $wa_scale = "y" ] && [ $wa_tran = "n" ]
then
	echo 'Cropping source video'
	echo 'Crop Width: '
	read wa_cropw
	echo ''
	echo 'Crop Height: '
	read wa_croph
	echo ''
	echo 'Resizing cropped video'
	echo 'Resize Width: '
	read wa_scalew
	echo ''
	echo 'Resize Height: '
	read wa_scaleh
	echo ''
	ffmpeg -ss $wa_off -i $wa_in -ss $wa_start -to $wa_end -vf "crop=$wa_cropw:$wa_croph:x:y,scale=$wa_scalew:$wa_scaleh" -preset faster -crf 18 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k $wa_out
fi

#1-0-0

if [ $wa_crop = "y" ] && [ $wa_scale = "n" ] && [ $wa_tran = "n" ]
then
	echo 'Cropping source video'
	echo 'Crop Width: '
	read wa_cropw
	echo ''
	echo 'Crop Height: '
	read wa_croph
	echo ''
	ffmpeg -ss $wa_off -i $wa_in -ss $wa_start -to $wa_end -vf "crop=$wa_cropw:$wa_croph:x:y" -preset faster -crf 18 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k $wa_out
fi

#0-1-1

if [ $wa_crop = "n" ] && [ $wa_scale = "y" ] && [ $wa_tran = "y" ]
then
	echo 'Resizing source video'
	echo 'Resize Width: '
	read wa_scalew
	echo ''
	echo 'Resize Height: '
	read wa_scaleh
	echo ''
	ffmpeg -ss $wa_off -i $wa_in -ss $wa_start -to $wa_end -vf "scale=$wa_scalew:$wa_scaleh,transpose=1" -preset faster -crf 18 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k $wa_out
fi

#0-1-0

if [ $wa_crop = "n" ] && [ $wa_scale = "y" ] && [ $wa_tran = "n" ]
then
	echo 'Resizing source video'
	echo 'Resize Width: '
	read wa_scalew
	echo ''
	echo 'Resize Height: '
	read wa_scaleh
	echo ''
	ffmpeg -ss $wa_off -i $wa_in -ss $wa_start -to $wa_end -vf "scale=$wa_scalew:$wa_scaleh" -preset faster -crf 18 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k $wa_out
fi

#0-0-1

if [ $wa_crop = "n" ] && [ $wa_scale = "n" ] && [ $wa_tran = "y" ]
then
	ffmpeg -ss $wa_off -i $wa_in -ss $wa_start -to $wa_end -vf "transpose=1" -preset faster -crf 18 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k $wa_out
fi

#0-0-0

if [ $wa_crop = "n" ] && [ $wa_scale = "n" ] && [ $wa_tran = "n" ]
then
	ffmpeg -ss $wa_off -i $wa_in -ss $wa_start -to $wa_end -preset faster -crf 18 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k $wa_out
fi
