#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# WaStatus - Banner

echo '-----------------------------------'
echo '    WhatsApp Status Creater Tool'
echo '-----------------------------------'
