#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# WaStatus - Video Module

wa_in=
wa_start=
wa_end=
wa_out=
wa_scale=
wa_crop=
wa_tran=
wa_cropw=
wa_croph=
wa_scalew=
wa_scaleh=
wa_maxdata=1692k
wa_bufsize=1692k

clear
banner
wastatus-banner

echo 'Video Status'
echo '------------'
echo ''
echo 'Input video file (with extension): '
read wa_in
echo ''
echo 'Start time in 00:00:00 format: '
read wa_start
echo ''
echo 'Length of video in seconds (from Start Time): '
read wa_end
echo ''
echo 'Output filename: '
read wa_out
echo ''

echo 'Crop Video (y/n): '
read wa_crop
echo ''
echo 'Resize video (y/n): '
read wa_scale
echo ''
echo 'Rotate 90° (y/n): '
read wa_tran
echo ''

#using binary for true or false
#crop-scale-transpose

#1-1-1

if [ $wa_crop = "y" ] && [ $wa_scale = "y" ] && [ $wa_tran = "y" ]
then
	echo 'Cropping source video'
	echo 'Crop Width: '
	read wa_cropw
	echo ''
	echo 'Crop Height: '
	read wa_croph
	echo ''
	echo 'Resizing cropped video'
	echo 'Resize Width: '
	read wa_scalew
	echo ''
	echo 'Resize Height: '
	read wa_scaleh
	echo ''
	ffmpeg -ss $wa_start -i "$wa_in" -t $wa_end -vf "crop=$wa_cropw:$wa_croph:x:y,scale=$wa_scalew:$wa_scaleh,transpose=1" -af "volume=1.5" -preset veryfast -crf 25 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k "$wa_out.mp4"
fi

#1-0-1

if [ $wa_crop = "y" ] && [ $wa_scale = "n" ] && [ $wa_tran = "y" ]
then
	echo 'Cropping source video'
	echo 'Crop Width: '
	read wa_cropw
	echo ''
	echo 'Crop Height: '
	read wa_croph
	echo ''
	ffmpeg -ss $wa_start -i "$wa_in" -t $wa_end -vf "crop=$wa_cropw:$wa_croph:x:y,transpose=1" -af "volume=1.5" -preset veryfast -crf 25 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k "$wa_out.mp4"
fi

#1-1-0

if [ $wa_crop = "y" ] && [ $wa_scale = "y" ] && [ $wa_tran = "n" ]
then
	echo 'Cropping source video'
	echo 'Crop Width: '
	read wa_cropw
	echo ''
	echo 'Crop Height: '
	read wa_croph
	echo ''
	echo 'Resizing cropped video'
	echo 'Resize Width: '
	read wa_scalew
	echo ''
	echo 'Resize Height: '
	read wa_scaleh
	echo ''
	ffmpeg -ss $wa_start -i "$wa_in" -t $wa_end -vf "crop=$wa_cropw:$wa_croph:x:y,scale=$wa_scalew:$wa_scaleh" -af "volume=1.5" -preset veryfast -crf 25 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k "$wa_out.mp4"
fi

#1-0-0

if [ $wa_crop = "y" ] && [ $wa_scale = "n" ] && [ $wa_tran = "n" ]
then
	echo 'Cropping source video'
	echo 'Crop Width: '
	read wa_cropw
	echo ''
	echo 'Crop Height: '
	read wa_croph
	echo ''
	ffmpeg -ss $wa_start -i "$wa_in" -t $wa_end -vf "crop=$wa_cropw:$wa_croph:x:y" -af "volume=1.5" -preset veryfast -crf 25 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k "$wa_out.mp4"
fi

#0-1-1

if [ $wa_crop = "n" ] && [ $wa_scale = "y" ] && [ $wa_tran = "y" ]
then
	echo 'Resizing source video'
	echo 'Resize Width: '
	read wa_scalew
	echo ''
	echo 'Resize Height: '
	read wa_scaleh
	echo ''
	ffmpeg -ss $wa_start -i "$wa_in" -t $wa_end -vf "scale=$wa_scalew:$wa_scaleh,transpose=1" -af "volume=1.5" -preset veryfast -crf 25 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k "$wa_out.mp4"
fi

#0-1-0

if [ $wa_crop = "n" ] && [ $wa_scale = "y" ] && [ $wa_tran = "n" ]
then
	echo 'Resizing source video'
	echo 'Resize Width: '
	read wa_scalew
	echo ''
	echo 'Resize Height: '
	read wa_scaleh
	echo ''
	ffmpeg -ss $wa_start -i "$wa_in" -t $wa_end -vf "scale=$wa_scalew:$wa_scaleh" -af "volume=1.5" -preset veryfast -crf 25 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k "$wa_out.mp4"
fi

#0-0-1

if [ $wa_crop = "n" ] && [ $wa_scale = "n" ] && [ $wa_tran = "y" ]
then
	ffmpeg -ss $wa_start -i "$wa_in" -t $wa_end -vf "transpose=1" -af "volume=1.5" -preset veryfast -crf 25 -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k "$wa_out.mp4"
fi

#0-0-0

if [ $wa_crop = "n" ] && [ $wa_scale = "n" ] && [ $wa_tran = "n" ]
then
	ffmpeg -ss $wa_start -i "$wa_in" -t $wa_end -preset veryfast -crf 25 -af "volume=1.5" -maxrate:v $wa_maxdata -bufsize $wa_bufsize -movflags +faststart -tune fastdecode -tune zerolatency -b:a 64k "$wa_out.mp4"
fi

echo ''
echo 'Task finished.'
echo 'Press ENTER to return to wastatus'
read tmp
wastatus
