#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# Initial Date: 09/May/2020
# Current Date: 09/May/2020
# Index page

i=4

clear
banner

echo '1. WaStatus'
echo '2. aria2 Manager'
echo '3. youtube-dl (soon)'
echo '4. Exit this menu'

read i
if [ $i -eq 1 ]
then
	wastatus
elif [ $i -eq 2 ]
then
	aria2manager
elif [ $i -eq 3 ]
then
	index
else
	clear
fi
