#!/data/data/com.termux/files/usr/bin/bash
# Author: Adithya S Sekhar
# Initial Date: 09/May/2020
# Current Date: 09/May/2020
# WaStatus - Primary Module

x=

clear
header
wastatus-header

echo '1. Video status'
echo '2. Audio status'

read x

if [ $x -eq 1 ]
then
 wastatus-video
elif [ $x -eq 2 ]
then
 wastatus-audio
else
 wastatus
fi
